### ISSUE TITLE
Prevents Krita from launching.

### ISSUE THREAD

**Issue by defEndrr** [Firstbober/Krita-rpc#6]
Krita seems to just freeze out on "Loading Main Window" with this plugin enabled. Running the latest version. Just as a hands up, tried resetting configs and re-starting after enabling rich presence freezes out the app. If there are any logs I can provide, please let me know.

**Comment by Firstbober** [comment]
What operating system are you using? If you can, attach Krita usage log after removing `krita-rpc`. It is located in `Help` tab as shown on the screenshot and contains 10 last Krita sessions, which should include crashing one before plugin removal.
![image](https://user-images.githubusercontent.com/22197465/198869248-9bb28d0a-c13c-47c6-84be-68509a99d5c7.png)

**Comment by defEndrr** [comment]
Good news or bad news, I have no idea.
First of all - during my misadventures with this, I've had a power outage, which subsequently rebooted my PC. When I booted back, Krita was launching normally. I'd say "disregard, sorry for wasting your time", yet I have logs of launches with freezes, which I'll share regardless. Honestly, looking through it now, I don't think anything of value can be gathered there. And now that I cannot replicate the issue, well...

```
SESSION: 30 Oct 2022 01:10:59 +0300. Executing C:\Program Files\Krita (x64)\bin\krita.exe

Krita Version: 5.1.1, Qt version compiled: 5.12.12, loaded: 5.12.12. Process ID: 25860
-- -- -- -- -- -- -- --
30 Oct 2022 01:10:59 +0300: Style: fusion. Available styles: windowsvista, Windows, Fusion
30 Oct 2022 01:11:01 +0300: Database is up to date. Version: 0.0.17, created by Krita 5.1.0, at Ср авг 24 10:08:17 2022
30 Oct 2022 01:11:03 +0300: Non-store package - creating updater
================================================================================
```
I assume those correspond to those sessions that froze out. Time checks out.
Oh, and to answer your first question, I'm using Windows 10. Dunno if anything can come out of it, so close at your own volition.

**Comment by Firstbober** [comment]
Maybe it was all just a random bit flip in ram. I guess we'll never know until this issue comes up again. Thanks for bug report and have a great day!
