### ISSUE TITLE
Support for arrpc

### ISSUE THREAD

**Issue by starget24** [Firstbober/Krita-rpc#8]
[Open source implementation of rich presence](https://github.com/OpenAsar/arrpc).

when i tried to run the krita app with the plugin enable this is what it put out in relation with the plugin 
```
/app/lib/krita-python-libs/krita added to PYTHONPATH
krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/discord_rpc/__init__.py\", line 1, in <module>"
krita.scripting: "    from .discord_rpc import *"
krita.scripting: "  File \"/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/discord_rpc/discord_rpc.py\", line 12, in <module>"
krita.scripting: "    RPC = Presence(DISCORD_RPC_CLIENT_ID)  # Initialize the client class"
krita.scripting: "  File \"/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/discord_rpc/presence.py\", line 13, in __init__"
krita.scripting: "    super().__init__(*args, **kwargs)"
krita.scripting: "  File \"/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/discord_rpc/baseclient.py\", line 28, in __init__"
krita.scripting: "    raise DiscordNotFound"
krita.scripting: "DiscordNotFound: Could not find Discord installed and running on this machine."
krita.scripting: "Could not import discord_rpc"
krita.scripting: Error loading plugin "discord_rpc"
```
Even when running an arrpc server.
It would be nice to not having to rely on the official rpc that includes proprietary libraries.

**Comment by Firstbober** [comment]
Can you reproduce this issue with standard discord RPC?

**Comment by starget24** [comment]
Investigated further and manage to make the plugin working with the arrpc server.
It was a problem with permissions inside the flatpak sandbox, native packages work as intended, on flatpak the permissions needed are these 
![image](https://github.com/Firstbober/krita-rpc/assets/92924912/aba3e9a6-f0cd-421a-8d63-4aac283586ce)
last command may differ depending on the client.
After putting those, the plugin works with no problems
![Screenshot from 2024-01-01 13-59-14](https://github.com/Firstbober/krita-rpc/assets/92924912/5fca66e5-54e2-4586-8b7e-caeb1395ba72)
Sorry for the confusion, the plugin itself works on both the arrpc and discord rpc servers.
